In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
# Convertir todo a minúscilas y separado con guión bajo
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [6]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [7]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

medium: robusto antes valores atípicos 
mean: puede afectar por valores atípicos (outlier) y puede sesgar (skew) la distribución de nuestros datos

si elegimos medium estamos forzando el mismo revoew ratings for clothings items y footwear items. Puede introducir preferencias en nuestro set de datos.
Imputar los valores nulos usando la media de review ratings dentro de cada categoría, asi usamos la media de review ratings para clothing con clothing,

In [8]:
df['review_rating'] = df.groupby('category')['review_rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [10]:
# Crear una columns age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [11]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [12]:
# Crear columna purchase_frequency_days
print(df['frequency_of_purchases'].unique())

['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']

In [13]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly' : 7,
    'Annually' : 365,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Monthly' : 30,
    'Every 3 Months' : 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

que tan frecuentemente compra un cliente. Hacemos un diccionarios con el equivalente en número y remplazamos el texto por el correspondiente número de días con map. Podemos ver el número

In [15]:
#df.columns

df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

Necesutamos ambas columnas? parece ser que ambas tienen los mismos valores, pero algunas veces se aplica un descuento sin necesidad de un código de promoción.

In [16]:
# Revisar redundancia 

(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [17]:
df = df.drop('promo_code_used', axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [25]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /opt/anaconda3/envs/telecom/lib/python3.10/site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/envs/telecom/lib/python3.10/site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in /opt/anaconda3/envs/telecom/lib/python3.10/site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/envs/telecom/lib/python3.10/site-packages (from sqlalchemy) (4.12.2)

In [24]:
from sqlalchemy import create_engine

# Conectar a PostgreSQL
username = 'postgres'
password = 'koya1924se'
host = 'localhost'
port = '5435'
database = 'customer_behavior'

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Cargar Dataframe en PostgreSQL
table_name = 'customer' 
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Los datos se cargaron correctamente en la tabla '{table_name}' en la base de datos '{database}'.")

Los datos se cargaron correctamente en la tabla 'customer' en la base de datos 'customer_behavior'.

In [21]:
print(df.shape)
print(df.head())

(3900, 19)
   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases    age_group  purchase_frequency_days
0            Fortnightly  Middle-aged                       14
1            Fortnightly  Young Adult                       14
2                 Weekly  Middle-aged                        7
3                 Weekly  Young Adult                        7
4               Annually  Middle-aged                      365

In [26]:
# What is the total revenue generated by male vs. female customer?

query = """
SELECT 
    gender, 
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
"""

gender_revenue = pd.read_sql(query, engine)

In [27]:
gender_revenue

   gender   revenue
0  Female   75191.0
1    Male  157890.0

better target in campain

In [30]:
# Wich customers used a discount but still spent more than average purchase amount?

query = """
SELECT 
    customer_id, 
    category,
    purchase_amount
FROM customer 
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (
    SELECT AVG(purchase_amount) 
    FROM customer
);
"""

discount_high_spenders = pd.read_sql(query, engine)

In [31]:
discount_high_spenders.head(10)

   customer_id   category  purchase_amount
0            2   Clothing               64
1            3   Clothing               73
2            4   Footwear               90
3            7   Clothing               85
4            9  Outerwear               97
5           12   Clothing               68
6           13  Outerwear               72
7           16   Clothing               81
8           20   Clothing               90
9           22   Clothing               62

In [38]:
# Which are the top 5 products with the highest average review ratings?

query = """
SELECT 
    item_purchased,
    ROUND(AVG(review_rating::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
"""

highest_avg_ratings = pd.read_sql(query, engine)

In [42]:
highest_avg_ratings

  item_purchased  Average Product Rating
0         Gloves                    3.86
1        Sandals                    3.84
2          Boots                    3.82
3            Hat                    3.80
4          Skirt                    3.78

In [50]:
# Compare the average Purchase Amounts between Standard and Express Shipping

query = """
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
"""

standar_vs_express = pd.read_sql(query, engine)

In [51]:
standar_vs_express

  shipping_type  round
0      Standard  58.46
1       Express  60.48

In [55]:
# Do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers

query = """
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customer,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY 
    total_revenue, 
    avg_spend DESC;
"""

avg_spend = pd.read_sql(query, engine)

In [56]:
avg_spend

  subscription_status  total_customer  avg_spend  total_revenue
0                 Yes            1053      59.49        62645.0
1                  No            2847      59.87       170436.0

In [66]:
# Which 5 products have the highest percentage of purchase with discounts applied?

query = """
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2)
    AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
"""

highest_percentage_item = pd.read_sql(query, engine)

In [67]:
highest_percentage_item

  item_purchased  discount_rate
0            Hat           50.0
1       Sneakers           49.0
2           Coat           49.0
3        Sweater           48.0
4          Pants           47.0

In [73]:
# Segment customer into New, Returning, and Loyal based on total number of previous
# purchases, and show the count of each segment

query = """
WITH customer_type AS(
SELECT 
    customer_id, 
    previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)

SELECT 
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;
"""

customer_type = pd.read_sql(query, engine)

In [74]:
customer_type

  customer_segment  Number of Customers
0            Loyal                 3116
1              New                   83
2        Returning                  701

In [77]:
# What are the top 3 most purchased products within each category?

query = """
WITH item_counts AS (
SELECT 
    category,
    item_purchased,
    COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER (PARTITION BY category
    ORDER BY COUNT (customer_id) DESC) AS item_rank
FROM customer
GROUP BY
    category,
    item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3;
"""

item_count = pd.read_sql(query, engine)

In [78]:
item_count

    item_rank     category item_purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing         Blouse           171
4           2     Clothing          Pants           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

por qué ROW NUMBER? para muchos items el número es el mismo. De otra forma sunglasses y belt estarían como rank 2, solo se necesita el rango 3 de cada categoría

In [80]:
# Are customers who are repeat buyesr (more than 5 previous purchases) also likely to subscribe?

query = """
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
"""

repeat_buyers = pd.read_sql(query, engine)

La oferta de subscribción es suficientemente atractiva para los clientes?

In [81]:
repeat_buyers

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

In [82]:
# What is the revenue contribution of each age group?

query = """
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
"""

age_revenue = pd.read_sql(query, engine)

In [83]:
age_revenue

     age_group  total_revenue
0  Young Adult        62143.0
1  Middle-aged        59197.0
2        Adult        55978.0
3       Senior        55763.0

In [84]:
df.to_csv('customer_shopping_behavior_clean.csv', index=False)

In [85]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')